lesson5
xRuTeRx/Golang pull request #6
Opened 2021-07-21 17:37 UTC by xRuTeRx

2021-07-26 10:04 UTC, denislituev approved these changes

2021-07-26 10:52 UTC, nikonok requested changes
You have a low coverage at unit tests. I think you can do it better!=)
Maybe that https://medium.com/rungo/unit-testing-made-easy-in-go-25077669318 will help you to improve some metrics.
Let me know if you can't change the coverage=)

2021-07-26 10:52 UTC, nikonok commented on .vscode/launch.json
> +{
Here is no need for such files from .vscode directory at requests. Please, read about .gitignore files=)

2021-08-02 15:20 UTC, xRuTeRx commented
func (r Rectangle) String () string and func (c Circle) String () string i think do not need coverage.
func DescribeShape returns no value. As I understand it, you cannot write a unit test for it

2021-08-06 10:45 UTC, nikonok approved these changes

2021-08-08 12:22 UTC, merged