lesson6
xRuTeRx/Golang pull request #7
Opened 2021-07-25 07:11 UTC by xRuTeRx

2021-07-28 21:06 UTC, denislituev requested changes

2021-07-28 21:06 UTC, denislituev commented on lesson6/task2/server/server.go
> +	case "GET":
better to use constants from http package here
see https://pkg.go.dev/net/http#pkg-constants

2021-07-28 21:06 UTC, denislituev commented on lesson6/task2/server/server.go
> +	case "POST":
better to use constants from http package here
see https://pkg.go.dev/net/http#pkg-constants

2021-07-28 21:06 UTC, denislituev commented on lesson6/task3/server/server.go
> +	case "GET":
please replace with constants

2021-07-28 21:06 UTC, denislituev commented on lesson6/task3/server/server.go
> +	case "POST":
same here

2021-07-30 09:53 UTC, nikonok requested changes

2021-07-30 09:53 UTC, nikonok commented on lesson6/task2/server/server.go
> +	http.HandleFunc("/", handler)
```
TCP Server (S) listen for a connections on a port
TCP Client (C) connects to a TCP server on a port 
```
TCP, not HTTP protocols, see my examples one more time=)

2021-08-02 21:29 UTC, denislituev approved these changes

2021-08-13 15:26 UTC, nikonok approved these changes

2021-08-13 15:39 UTC, merged