lesson7 Task2
xRuTeRx/Golang pull request #8
Opened 2021-07-28 18:33 UTC by xRuTeRx

2021-08-03 20:43 UTC, denislituev requested changes
good job, please fix comments and fix string errors even if I missed it

2021-08-03 20:43 UTC, denislituev commented on lesson7/task2/cmd/server/main.go
> +	endpoint := "/rpc"
do not need here separate variable for endpoint

2021-08-03 20:43 UTC, denislituev commented on lesson7/task2/handlers/handle.go
> +		return nil, errors.New("failed to read request body")
It is good GO style to have a block of constants in the top of the file with all errors messages

2021-08-03 20:43 UTC, denislituev commented on lesson7/task2/handlers/handle.go
> +		return nil, errors.New("request format is wrong")
also could move string literal to const block

2021-08-03 20:43 UTC, denislituev commented on lesson7/task2/handlers/handle.go
> +		return nil, errors.New(fmt.Sprintf("method %s is not supported", req.Method))
also could move string literal to const block

2021-08-03 20:43 UTC, denislituev commented on lesson7/task2/handlers/methods/list.go
> +		return "", errors.New("wrong params sent, expected {name:string}")
same here

2021-08-03 20:43 UTC, denislituev commented on lesson7/task2/cmd/client/main.go
> +	const port = 8081
this const could be declared out of main()

2021-08-03 20:43 UTC, denislituev commented on lesson7/task2/cmd/client/main.go
> +	address := fmt.Sprintf("http://localhost:%d/rpc", port)
also make this string as const - this will be look better

2021-08-06 09:42 UTC, nikonok approved these changes

2021-08-08 14:56 UTC, denislituev approved these changes

2021-08-08 19:19 UTC, merged